const KEYWORDS_RU = [
  "e-commerce",
  "ecommerce",
  "электронная коммерция",
  "электронной коммерции",
  "интернет-торговл",
  "онлайн-торговл",
  "онлайн торговл",
  "маркетплейс",
  "ozon",
  "wildberries",
  "яндекс маркет",
  "яндекс.маркет",
  "алиэкспресс",
  "алибаба",
  "шопифа",
  "кэшбэк",
  "big tech",
  "bigtech",
  "цифровые платформ",
  "цифровая платформа",
  "цифровой платформы",
  "it-гигант",
  "айти-гигант",
  "антимонопольн",
  "антимонопольная служба",
  "антимонопольное регулирование",
  "фас",
  "федеральная антимонопольная",
  "защита конкуренции",
  "доминирующее положение",
  "злоупотребление доминирующим",
  "монополи",
  "самопредпочтение",
  "привратник",
  "сетевой эффект",
  "онлайн-ритейл",
  "онлайн ритейл",
  "интернет-магазин",
  "цифровая экономик",
  "платформенная экономика",
  "онлайн-платформ",
  "цифровой рынок",
  "цифровые рынк",
  "переносимость данных",
  "магазин приложений",
  "расследование",
  "штраф",
  "предупреждение",
  "предписание",
  "сделка",
  "поглощение",
  "сбер",
  "mail.ru",
  "vk",
  "цифровой рубль",
  "электронная торговая площадк",
  "омниканальн",
  "b2b",
  "b2c",
  "d2c",
  "кросс-граничная торговля",
  "трансграничная торговля",
  "доставка",
  "логистик",
  "быстрая доставка",
  "пункт выдачи",
  "пвз",
  "сортировочный центр",
  "интернет-реклам",
  "таргетированная реклам",
  "персональные данные",
  "цифровой суверенитет",
  "импортозамещение",
  "технологический суверенитет",
  "цифровая безопасность",
  "утечка данных",
];

const KEYWORDS_EN = [
  "ecommerce",
  "e-commerce",
  "e commerce",
  "online retail",
  "online shopping",
  "marketplace",
  "alibaba",
  "ebay",
  "shopify",
  "walmart",
  "big tech",
  "antitrust",
  "anti-trust",
  "dominant position",
  "abuse of dominance",
  "monopoly",
  "monopolistic",
  "digital platform",
  "platform economy",
  "digital economy",
  "digital market",
  "online platform",
  "tech giant",
  "amazon",
  "meta",
  "alphabet",
  "tesla",
  "uber",
  "delivery",
  "logistics",
  "fintech",
  "payment system",
  "digital payment",
  "bnpl",
  "buy now pay later",
  "cashback",
  "fulfillment",
  "last mile",
  "cross-border",
  "d2c",
  "b2b",
  "b2c",
  "saas",
  "cloud computing",
  "gatekeeper",
  "data portability",
  "interoperability",
  "network effect",
  "omnichannel",
  "artificial intelligence",
  "machine learning",
  "data privacy",
  "data breach",
  "personal data",
  "app store",
  "live commerce",
  "quick commerce",
  "self-preferencing",
  "social commerce",
  "digital services act",
  "digital markets act",
  "dma",
  "dsa",
  "merger",
  "acquisition",
  "ipo",
  "startup",
  "venture capital",
  "unicorn",
  "retail tech",
  "ad tech",
  "programmatic advertising",
  "targeted advertising",
];

export function isRelevantNews(title: string, annotation: string): boolean {
  const text = `${title} ${annotation}`.toLowerCase();

  for (const kw of KEYWORDS_RU) {
    if (text.includes(kw.toLowerCase())) return true;
  }

  for (const kw of KEYWORDS_EN) {
    if (text.includes(kw.toLowerCase())) return true;
  }

  return false;
}
